spring:
  application:
    name: codecoachai-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import:
      - optional:nacos:codecoachai-common-${spring.profiles.active}.yml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:codecoachai-redis-${spring.profiles.active}.yml?group=DEFAULT_GROUP&refreshEnabled=true
      - optional:nacos:codecoachai-gateway-${spring.profiles.active}.yml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        group: DEFAULT_GROUP
        namespace: ${NACOS_NAMESPACE}
        username: ${NACOS_USERNAME:}
        password: ${NACOS_PASSWORD:}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        group: DEFAULT_GROUP
        file-extension: yml
        namespace: ${NACOS_NAMESPACE}
        username: ${NACOS_USERNAME:}
        password: ${NACOS_PASSWORD:}
