<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.codecoachai</groupId>
        <artifactId>codecoachai-java</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>codecoachai-core</artifactId>
    <name>codecoachai-core</name>

    <dependencies>
        <dependency>
            <groupId>com.codecoachai</groupId>
            <artifactId>codecoachai-auth</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.codecoachai</groupId>
            <artifactId>codecoachai-user</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.codecoachai</groupId>
            <artifactId>codecoachai-system</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.codecoachai</groupId>
            <artifactId>codecoachai-file</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.codecoachai</groupId>
            <artifactId>codecoachai-resume</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.codecoachai</groupId>
            <artifactId>codecoachai-question</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.codecoachai</groupId>
            <artifactId>codecoachai-interview</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.codecoachai</groupId>
            <artifactId>codecoachai-task</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
