-- V2 A6: industry templates and industry-scene interview snapshots.

CREATE TABLE IF NOT EXISTS industry_template (
  id BIGINT NOT NULL AUTO_INCREMENT,
  industry_code VARCHAR(64) NOT NULL COMMENT '行业编码',
  industry_name VARCHAR(100) NOT NULL COMMENT '行业名称',
  description VARCHAR(500) DEFAULT NULL COMMENT '行业说明',
  target_positions VARCHAR(500) DEFAULT NULL COMMENT '适用岗位',
  core_business_scenarios LONGTEXT DEFAULT NULL COMMENT '核心业务场景 JSON',
  key_technical_points LONGTEXT DEFAULT NULL COMMENT '关键技术关注点 JSON',
  common_question_directions LONGTEXT DEFAULT NULL COMMENT '常见追问方向 JSON',
  risk_points LONGTEXT DEFAULT NULL COMMENT '常见风险点 JSON',
  prompt_context LONGTEXT DEFAULT NULL COMMENT '注入 AI Prompt 的行业上下文',
  enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_industry_code (industry_code),
  KEY idx_enabled_sort (enabled, sort_order),
  KEY idx_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='行业模板';

ALTER TABLE interview_session
  ADD COLUMN industry_template_id BIGINT DEFAULT NULL COMMENT '行业模板ID' AFTER experience_level,
  ADD COLUMN industry_context LONGTEXT DEFAULT NULL COMMENT '行业上下文快照' AFTER industry_direction;

INSERT INTO industry_template (
  industry_code, industry_name, description, target_positions,
  core_business_scenarios, key_technical_points, common_question_directions, risk_points,
  prompt_context, enabled, sort_order
) VALUES
  ('ECOMMERCE', '电商', '面向交易、商品、营销和履约链路的后端场景。', 'Java 后端,电商后端,交易系统开发',
   '["订单","库存","支付","秒杀","营销","售后","商品搜索"]',
   '["高并发扣减","缓存一致性","支付幂等","订单状态机","搜索性能"]',
   '["如何保证库存一致性","支付回调如何幂等","秒杀链路如何削峰"]',
   '["超卖","重复支付","缓存击穿","订单状态不一致"]',
   '电商场景关注订单、库存、支付、营销和售后链路，提问时优先考察一致性、幂等、高并发和异常补偿。', 1, 10),
  ('FINANCE_PAYMENT', '金融支付', '面向支付、账务、风控和对账的后端场景。', 'Java 后端,支付系统开发,金融科技后端',
   '["支付回调","账务一致性","风控","对账","退款"]',
   '["幂等设计","分布式事务取舍","资金安全","审计日志","异常补偿"]',
   '["支付回调乱序如何处理","账务差异如何排查","风控规则如何落地"]',
   '["重复入账","资损","回调丢失","对账遗漏"]',
   '金融支付场景关注资金安全、幂等、对账、风控和审计，提问时必须区分真实经历和假设迁移能力。', 1, 20),
  ('ONLINE_EDUCATION', '在线教育', '面向课程、排课、直播和学习进度的业务场景。', 'Java 后端,在线教育后端,教学平台开发',
   '["课程","排课","直播","作业","学习进度"]',
   '["排课冲突","直播状态","学习记录一致性","内容权限","异步任务"]',
   '["如何设计课程进度","排课冲突如何校验","直播回放如何关联"]',
   '["进度丢失","权限越权","排课冲突","消息延迟"]',
   '在线教育场景关注课程、排课、直播、作业和学习进度，提问时关注状态流转、权限和学习数据一致性。', 1, 30),
  ('SAAS', '企业 SaaS', '面向多租户、组织、权限和订阅计费的企业服务场景。', 'Java 后端,SaaS 后端,企业应用开发',
   '["租户隔离","权限","订阅计费","组织架构","审计"]',
   '["多租户隔离","RBAC","数据权限","计费状态","审计日志"]',
   '["租户数据如何隔离","权限模型如何设计","订阅到期如何处理"]',
   '["租户越权","权限膨胀","计费状态不一致","审计缺失"]',
   'SaaS 场景关注租户隔离、组织权限、订阅计费和审计，提问时关注权限边界和数据隔离。', 1, 40),
  ('CONTENT_COMMUNITY', '内容社区', '面向内容生产、互动、审核和推荐的社区场景。', 'Java 后端,社区后端,内容平台开发',
   '["内容审核","推荐","评论","点赞","反作弊"]',
   '["审核流","计数一致性","Feed 流","反作弊","热点内容缓存"]',
   '["点赞计数如何保证","内容审核如何异步化","评论反作弊如何设计"]',
   '["刷赞","违规内容漏审","热点缓存失效","计数不一致"]',
   '内容社区场景关注内容审核、互动计数、推荐和反作弊，提问时关注异步化、热点和一致性。', 1, 50),
  ('ERP_LOGISTICS', '物流 / ERP', '面向库存、仓储、调度和订单流转的业务场景。', 'Java 后端,ERP 后端,物流系统开发',
   '["库存","仓储","调度","订单流转","出入库"]',
   '["库存流水","状态机","调度策略","批量导入导出","权限边界"]',
   '["库存流水如何设计","订单流转如何保证一致","调度失败如何补偿"]',
   '["库存账实不符","状态回退混乱","批处理失败","越权操作"]',
   '物流 ERP 场景关注库存、仓储、调度和订单流转，提问时关注状态机、流水、批处理和补偿。', 1, 60),
  ('GENERAL_BACKEND', '通用后台', '面向管理后台和通用业务系统的后端场景。', 'Java 后端,后台开发,管理系统开发',
   '["RBAC","审计日志","数据权限","导入导出","配置管理"]',
   '["权限模型","操作审计","数据范围","批量任务","接口幂等"]',
   '["RBAC 如何设计","数据权限如何落地","导入失败如何处理"]',
   '["权限越权","审计缺失","批量任务阻塞","数据污染"]',
   '通用后台场景关注 RBAC、审计日志、数据权限和导入导出，适合作为默认行业迁移能力考察。', 1, 70)
ON DUPLICATE KEY UPDATE
  industry_name = VALUES(industry_name),
  description = VALUES(description),
  target_positions = VALUES(target_positions),
  core_business_scenarios = VALUES(core_business_scenarios),
  key_technical_points = VALUES(key_technical_points),
  common_question_directions = VALUES(common_question_directions),
  risk_points = VALUES(risk_points),
  prompt_context = VALUES(prompt_context),
  enabled = VALUES(enabled),
  sort_order = VALUES(sort_order);
