CREATE TABLE IF NOT EXISTS `agent_context_usage_reference` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `source_type` VARCHAR(64) NOT NULL COMMENT 'source type',
    `source_id` BIGINT NOT NULL COMMENT 'source business id',
    `source_version` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'source version or normalization version',
    `consumer_type` VARCHAR(64) NOT NULL COMMENT 'consumer type',
    `consumer_id` BIGINT NOT NULL COMMENT 'consumer business id',
    `trace_id` VARCHAR(128) DEFAULT NULL COMMENT 'consumer trace id',
    `usage_scene` VARCHAR(64) NOT NULL COMMENT 'usage scene',
    `usage_strength` VARCHAR(16) NOT NULL DEFAULT 'MEDIUM' COMMENT 'WEAK/MEDIUM/STRONG',
    `confidence` DECIMAL(5,2) NOT NULL DEFAULT 1.00 COMMENT '0.00-1.00 confidence',
    `snapshot_hash` CHAR(64) DEFAULT NULL COMMENT 'sha256 snapshot hash, no raw text',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_acur_live_ref` (`user_id`, `source_type`, `source_id`, `source_version`, `consumer_type`, `consumer_id`, `usage_scene`, `deleted`),
    KEY `idx_acur_source` (`user_id`, `source_type`, `source_id`, `deleted`, `created_at`),
    KEY `idx_acur_consumer` (`user_id`, `consumer_type`, `consumer_id`, `deleted`, `created_at`),
    KEY `idx_acur_trace` (`trace_id`, `deleted`, `created_at`),
    KEY `idx_acur_scene_strength` (`user_id`, `usage_scene`, `usage_strength`, `deleted`, `created_at`),
    KEY `idx_acur_hash` (`snapshot_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='agent context usage reference without sensitive raw content';
