CREATE TABLE IF NOT EXISTS `job_readiness_snapshot` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `target_job_id` BIGINT NOT NULL COMMENT 'target job id',
    `jd_analysis_id` BIGINT NOT NULL COMMENT 'source JD analysis id',
    `snapshot_hash` VARCHAR(64) NOT NULL COMMENT 'deterministic matrix input fingerprint',
    `policy_version` VARCHAR(64) NOT NULL COMMENT 'readiness scoring policy version',
    `readiness_score` INT NOT NULL COMMENT 'evidence weighted readiness score 0-100',
    `readiness_level` VARCHAR(32) NOT NULL COMMENT 'READY/NEAR_READY/NEEDS_WORK',
    `confidence_level` VARCHAR(32) NOT NULL COMMENT 'LOW/MEDIUM/HIGH',
    `fallback` TINYINT NOT NULL DEFAULT 0 COMMENT 'snapshot contains fallback or low confidence requirements',
    `requirement_count` INT NOT NULL DEFAULT 0,
    `strong_count` INT NOT NULL DEFAULT 0,
    `weak_count` INT NOT NULL DEFAULT 0,
    `missing_count` INT NOT NULL DEFAULT 0,
    `must_requirement_count` INT NOT NULL DEFAULT 0,
    `must_missing_count` INT NOT NULL DEFAULT 0,
    `summary_json` LONGTEXT NOT NULL COMMENT 'scoring evidence summary',
    `matrix_json` LONGTEXT NOT NULL COMMENT 'immutable requirement matrix snapshot',
    `generated_at` DATETIME NOT NULL COMMENT 'snapshot generation time',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_job_readiness_snapshot_hash` (`user_id`, `target_job_id`, `snapshot_hash`),
    KEY `idx_job_readiness_target_latest` (`user_id`, `target_job_id`, `deleted`, `generated_at`, `id`),
    KEY `idx_job_readiness_analysis` (`jd_analysis_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='evidence backed target job readiness snapshots';
