CREATE TABLE IF NOT EXISTS `interview_voice_device_check` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `session_id` BIGINT NOT NULL COMMENT 'interview session id',
    `permission_state` VARCHAR(32) NOT NULL COMMENT 'browser microphone permission state',
    `sample_rate_hz` INT DEFAULT NULL COMMENT 'captured sample rate',
    `channels` INT DEFAULT NULL COMMENT 'captured channel count',
    `input_detected` TINYINT NOT NULL DEFAULT 0 COMMENT 'whether client observed microphone input',
    `echo_cancellation` TINYINT DEFAULT NULL COMMENT 'browser echo cancellation constraint',
    `noise_suppression` TINYINT DEFAULT NULL COMMENT 'browser noise suppression constraint',
    `auto_gain_control` TINYINT DEFAULT NULL COMMENT 'browser automatic gain constraint',
    `average_rms_dbfs` DECIMAL(7,3) DEFAULT NULL COMMENT 'client measured average RMS in dBFS',
    `clipping_ratio` DECIMAL(7,6) DEFAULT NULL COMMENT 'client measured clipped sample ratio',
    `check_status` VARCHAR(32) NOT NULL COMMENT 'PASS/WARN/FAIL',
    `warning_codes` VARCHAR(500) DEFAULT NULL COMMENT 'comma-separated observable device warnings',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    PRIMARY KEY (`id`),
    KEY `idx_ivdc_user_session` (`user_id`, `session_id`, `deleted`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='observable microphone device checks without device fingerprinting';

CREATE TABLE IF NOT EXISTS `interview_voice_delivery_analysis` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `session_id` BIGINT NOT NULL COMMENT 'interview session id',
    `voice_submission_id` BIGINT DEFAULT NULL COMMENT 'optional voice submission id',
    `device_check_id` BIGINT DEFAULT NULL COMMENT 'optional device check id',
    `task_status` VARCHAR(32) NOT NULL DEFAULT 'QUEUED' COMMENT 'QUEUED/RUNNING/SUCCEEDED/FAILED/CANCELLED/TIMED_OUT',
    `timestamp_source` VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT 'NONE/CLIENT/PROVIDER',
    `timestamps_available` TINYINT NOT NULL DEFAULT 0 COMMENT 'whether real word timestamps were supplied',
    `audio_duration_ms` BIGINT DEFAULT NULL COMMENT 'observable audio duration',
    `word_count` INT DEFAULT NULL COMMENT 'observable transcript unit count',
    `speaking_rate_per_minute` DECIMAL(10,2) DEFAULT NULL COMMENT 'transcript units per minute',
    `filler_count` INT DEFAULT NULL COMMENT 'literal filler token count',
    `pause_metrics_available` TINYINT NOT NULL DEFAULT 0 COMMENT 'false when word timestamps are unavailable',
    `pause_count` INT DEFAULT NULL COMMENT 'count of timestamp gaps at least 500ms',
    `average_pause_ms` BIGINT DEFAULT NULL COMMENT 'average qualifying timestamp gap',
    `longest_pause_ms` BIGINT DEFAULT NULL COMMENT 'longest qualifying timestamp gap',
    `warning_codes` VARCHAR(500) DEFAULT NULL COMMENT 'comma-separated explainable warnings',
    `deadline_at` DATETIME NOT NULL COMMENT 'task deadline',
    `completed_at` DATETIME DEFAULT NULL COMMENT 'terminal completion time',
    `cancelled_at` DATETIME DEFAULT NULL COMMENT 'cancellation time',
    `error_code` VARCHAR(64) DEFAULT NULL COMMENT 'safe error code',
    `error_message` VARCHAR(500) DEFAULT NULL COMMENT 'safe error message',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    PRIMARY KEY (`id`),
    KEY `idx_ivda_user_session` (`user_id`, `session_id`, `deleted`, `created_at`),
    KEY `idx_ivda_status_deadline` (`task_status`, `deadline_at`, `deleted`),
    KEY `idx_ivda_submission` (`voice_submission_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='explainable voice delivery metrics; no emotion or personality inference';

CREATE TABLE IF NOT EXISTS `interview_audio_retention_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `session_id` BIGINT NOT NULL COMMENT 'interview session id',
    `voice_submission_id` BIGINT NOT NULL COMMENT 'voice submission id',
    `file_id` BIGINT NOT NULL COMMENT 'audio file id',
    `policy_code` VARCHAR(64) NOT NULL COMMENT 'retention policy code',
    `retain_until` DATETIME NOT NULL COMMENT 'earliest physical cleanup time',
    `legal_hold` TINYINT NOT NULL DEFAULT 0 COMMENT 'whether cleanup is administratively blocked',
    `retention_status` VARCHAR(32) NOT NULL DEFAULT 'RETAINED' COMMENT 'RETAINED/CLEANUP_PENDING/DELETED/CLEANUP_FAILED/CANCELLED',
    `cleanup_requested_at` DATETIME DEFAULT NULL COMMENT 'latest cleanup request time',
    `cleanup_completed_at` DATETIME DEFAULT NULL COMMENT 'verified physical deletion time',
    `last_error_code` VARCHAR(64) DEFAULT NULL COMMENT 'safe latest error code',
    `last_error_message` VARCHAR(500) DEFAULT NULL COMMENT 'safe latest error message',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_iarr_submission` (`voice_submission_id`),
    KEY `idx_iarr_due` (`retention_status`, `legal_hold`, `retain_until`, `deleted`),
    KEY `idx_iarr_user_session` (`user_id`, `session_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='audio retention policy state';

CREATE TABLE IF NOT EXISTS `interview_audio_cleanup_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `retention_record_id` BIGINT NOT NULL COMMENT 'audio retention record id',
    `cleanup_task_id` VARCHAR(96) NOT NULL COMMENT 'cancellable cleanup task id',
    `attempt_no` INT NOT NULL COMMENT 'monotonic cleanup attempt number',
    `cleanup_status` VARCHAR(32) NOT NULL COMMENT 'QUEUED/RUNNING/SUCCEEDED/FAILED/CANCELLED/TIMED_OUT',
    `provider_code` VARCHAR(32) NOT NULL DEFAULT 'FILE_SERVICE' COMMENT 'physical cleanup provider',
    `deadline_at` DATETIME NOT NULL COMMENT 'cleanup task deadline',
    `started_at` DATETIME DEFAULT NULL COMMENT 'attempt start time',
    `completed_at` DATETIME DEFAULT NULL COMMENT 'attempt terminal time',
    `error_code` VARCHAR(64) DEFAULT NULL COMMENT 'safe error code',
    `error_message` VARCHAR(500) DEFAULT NULL COMMENT 'safe error message',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_iacr_task` (`cleanup_task_id`),
    UNIQUE KEY `uk_iacr_attempt` (`retention_record_id`, `attempt_no`),
    KEY `idx_iacr_status_deadline` (`cleanup_status`, `deadline_at`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='append-only audio cleanup attempt records';
