CREATE TABLE IF NOT EXISTS `project_evidence` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `title` VARCHAR(128) NOT NULL COMMENT 'project title',
    `role` VARCHAR(128) DEFAULT NULL COMMENT 'project role',
    `start_date` VARCHAR(32) DEFAULT NULL COMMENT 'project start date text',
    `end_date` VARCHAR(32) DEFAULT NULL COMMENT 'project end date text',
    `background` TEXT DEFAULT NULL COMMENT 'business background',
    `responsibility` TEXT DEFAULT NULL COMMENT 'personal responsibility',
    `tech_stack` VARCHAR(512) DEFAULT NULL COMMENT 'technology stack',
    `difficulty` TEXT DEFAULT NULL COMMENT 'core difficulty',
    `solution` TEXT DEFAULT NULL COMMENT 'solution',
    `result` TEXT DEFAULT NULL COMMENT 'quantified result',
    `reflection` TEXT DEFAULT NULL COMMENT 'reflection',
    `completeness_score` INT NOT NULL DEFAULT 0 COMMENT 'completeness score',
    `completeness_status` VARCHAR(32) NOT NULL DEFAULT 'INCOMPLETE' COMMENT 'completeness status',
    `missing_fields` VARCHAR(512) DEFAULT NULL COMMENT 'missing field keys',
    `source_resume_id` BIGINT DEFAULT NULL COMMENT 'source resume id',
    `source_resume_project_id` BIGINT DEFAULT NULL COMMENT 'source resume project id',
    `target_job_id` BIGINT DEFAULT NULL COMMENT 'target job id',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    PRIMARY KEY (`id`),
    KEY `idx_project_evidence_user_update` (`user_id`, `deleted`, `updated_at`),
    KEY `idx_project_evidence_source` (`source_resume_id`, `source_resume_project_id`),
    KEY `idx_project_evidence_target_job` (`target_job_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='private project evidence material';

CREATE TABLE IF NOT EXISTS `project_skill_evidence` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `project_evidence_id` BIGINT NOT NULL COMMENT 'project evidence id',
    `skill_name` VARCHAR(128) NOT NULL COMMENT 'skill name',
    `skill_category` VARCHAR(64) DEFAULT NULL COMMENT 'skill category',
    `evidence_text` TEXT DEFAULT NULL COMMENT 'evidence text',
    `strength_level` VARCHAR(32) NOT NULL DEFAULT 'MEDIUM' COMMENT 'STRONG/MEDIUM/WEAK',
    `jd_keyword` VARCHAR(256) DEFAULT NULL COMMENT 'related JD keyword',
    `risk_points` TEXT DEFAULT NULL COMMENT 'interview risk points',
    `source_type` VARCHAR(32) NOT NULL DEFAULT 'MANUAL' COMMENT 'MANUAL/AI_EXTRACTED',
    `confirmed` TINYINT NOT NULL DEFAULT 1 COMMENT 'confirmed by user',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    PRIMARY KEY (`id`),
    KEY `idx_project_skill_evidence_project` (`project_evidence_id`, `deleted`),
    KEY `idx_project_skill_evidence_user` (`user_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='manual skill evidence for project material';
