CREATE TABLE IF NOT EXISTS `interview_voice_submission` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `session_id` BIGINT NOT NULL COMMENT 'interview session id',
    `question_message_id` BIGINT NOT NULL COMMENT 'current question message id',
    `question_id` BIGINT DEFAULT NULL COMMENT 'question bank id',
    `file_id` BIGINT NOT NULL COMMENT 'uploaded audio file id',
    `audio_duration_ms` BIGINT DEFAULT NULL COMMENT 'audio duration in milliseconds',
    `mime_type` VARCHAR(128) DEFAULT NULL COMMENT 'audio mime type',
    `voice_status` VARCHAR(32) NOT NULL DEFAULT 'UPLOADED' COMMENT 'UPLOADED/TRANSCRIBING/TRANSCRIBED/TRANSCRIBE_FAILED/CONFIRMED/DISCARDED',
    `trace_id` VARCHAR(128) DEFAULT NULL COMMENT 'voice chain trace id',
    `fallback` TINYINT NOT NULL DEFAULT 0 COMMENT 'whether ASR/manual fallback happened',
    `fallback_reason` VARCHAR(500) DEFAULT NULL COMMENT 'safe fallback reason',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    PRIMARY KEY (`id`),
    KEY `idx_ivs_user_session` (`user_id`, `session_id`, `deleted`, `updated_at`),
    KEY `idx_ivs_question_message` (`session_id`, `question_message_id`, `deleted`),
    KEY `idx_ivs_file` (`file_id`, `deleted`),
    KEY `idx_ivs_trace` (`trace_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='interview voice submission';

CREATE TABLE IF NOT EXISTS `interview_transcript` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `session_id` BIGINT NOT NULL COMMENT 'interview session id',
    `voice_submission_id` BIGINT NOT NULL COMMENT 'interview_voice_submission id',
    `question_message_id` BIGINT NOT NULL COMMENT 'current question message id',
    `question_id` BIGINT DEFAULT NULL COMMENT 'question bank id',
    `draft_text` TEXT DEFAULT NULL COMMENT 'ASR draft transcript, owner-only sensitive text',
    `confirmed_text` TEXT DEFAULT NULL COMMENT 'user confirmed transcript, owner-only sensitive text',
    `confidence` DECIMAL(5,2) DEFAULT NULL COMMENT 'ASR confidence 0.00-1.00',
    `transcript_status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/LOW_CONFIDENCE/CONFIRMED/REJECTED/FAILED',
    `asr_provider` VARCHAR(64) DEFAULT NULL COMMENT 'ASR provider code',
    `fallback` TINYINT NOT NULL DEFAULT 0 COMMENT 'whether ASR/manual fallback happened',
    `fallback_reason` VARCHAR(500) DEFAULT NULL COMMENT 'safe fallback reason',
    `trace_id` VARCHAR(128) DEFAULT NULL COMMENT 'voice chain trace id',
    `confirmed_at` DATETIME DEFAULT NULL COMMENT 'user confirmation time',
    `submitted_answer_message_id` BIGINT DEFAULT NULL COMMENT 'linked formal interview answer message id',
    `submitted_at` DATETIME DEFAULT NULL COMMENT 'formal answer submit time',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    PRIMARY KEY (`id`),
    KEY `idx_it_user_session` (`user_id`, `session_id`, `deleted`, `updated_at`),
    KEY `idx_it_submission` (`voice_submission_id`, `deleted`),
    KEY `idx_it_answer_message` (`submitted_answer_message_id`, `deleted`),
    KEY `idx_it_question_message` (`session_id`, `question_message_id`, `deleted`),
    KEY `idx_it_trace` (`trace_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='interview ASR transcript and confirmation';
