CREATE TABLE IF NOT EXISTS career_calendar_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    application_id BIGINT NULL,
    title VARCHAR(200) NOT NULL,
    event_type VARCHAR(40) NOT NULL DEFAULT 'FOLLOW_UP',
    starts_at_utc DATETIME NOT NULL,
    ends_at_utc DATETIME NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    all_day_flag TINYINT NOT NULL DEFAULT 0,
    location VARCHAR(300) NULL,
    description VARCHAR(2000) NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'CONFIRMED',
    source_type VARCHAR(24) NOT NULL DEFAULT 'MANUAL',
    source_ref VARCHAR(160) NULL,
    external_uid VARCHAR(255) NULL,
    import_batch_id BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_cce_user_external_uid (user_id, external_uid, deleted),
    KEY idx_cce_user_time (user_id, starts_at_utc, ends_at_utc, deleted),
    KEY idx_cce_application (application_id, deleted),
    KEY idx_cce_import_batch (import_batch_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM career calendar event stored in UTC with source timezone';

CREATE TABLE IF NOT EXISTS career_import_batch (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    format VARCHAR(16) NOT NULL,
    filename VARCHAR(255) NULL,
    timezone VARCHAR(64) NOT NULL,
    duplicate_policy VARCHAR(24) NOT NULL DEFAULT 'SKIP',
    status VARCHAR(24) NOT NULL DEFAULT 'RUNNING',
    total_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    error_count INT NOT NULL DEFAULT 0,
    duplicate_count INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_cib_user_created (user_id, created_at, deleted),
    KEY idx_cib_status (status, updated_at, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CSV/ICS import batch audit';

CREATE TABLE IF NOT EXISTS career_import_row (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    batch_id BIGINT NOT NULL,
    `row_number` INT NOT NULL,
    disposition VARCHAR(32) NOT NULL,
    raw_data_json TEXT NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(1000) NULL,
    duplicate_candidates_json TEXT NULL,
    application_id BIGINT NULL,
    calendar_event_id BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_cir_batch_row (batch_id, `row_number`, deleted),
    KEY idx_cir_user_batch (user_id, batch_id, disposition, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Per-row partial import result and duplicate candidates';
