CREATE TABLE IF NOT EXISTS `job_requirement` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `target_job_id` BIGINT NOT NULL COMMENT 'target job id',
    `jd_analysis_id` BIGINT NOT NULL COMMENT 'source JD analysis id',
    `requirement_key` VARCHAR(64) NOT NULL COMMENT 'deterministic requirement fingerprint',
    `requirement_type` VARCHAR(32) NOT NULL COMMENT 'SKILL/RESPONSIBILITY/EXPERIENCE/PROJECT_EXPERIENCE',
    `requirement_name` TEXT NOT NULL COMMENT 'normalized display name',
    `description` TEXT DEFAULT NULL COMMENT 'source requirement description',
    `category` VARCHAR(64) DEFAULT NULL COMMENT 'requirement category',
    `required_level` VARCHAR(64) DEFAULT NULL COMMENT 'required level',
    `priority` VARCHAR(32) NOT NULL COMMENT 'MUST/NICE_TO_HAVE',
    `weight` DECIMAL(10,4) NOT NULL DEFAULT 1.0000 COMMENT 'relative readiness weight',
    `confidence_level` VARCHAR(32) NOT NULL DEFAULT 'MEDIUM' COMMENT 'LOW/MEDIUM/HIGH',
    `source_field` VARCHAR(64) NOT NULL COMMENT 'JD analysis source field',
    `source_json` LONGTEXT DEFAULT NULL COMMENT 'source item JSON snapshot',
    `source_fallback` TINYINT NOT NULL DEFAULT 0 COMMENT 'source is fallback or degraded',
    `active_flag` TINYINT NOT NULL DEFAULT 1 COMMENT 'active in latest materialization',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_job_requirement_analysis_key` (`user_id`, `target_job_id`, `jd_analysis_id`, `requirement_key`),
    KEY `idx_job_requirement_target_active` (`user_id`, `target_job_id`, `active_flag`, `deleted`),
    KEY `idx_job_requirement_analysis` (`jd_analysis_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='materialized deterministic JD requirements';

CREATE TABLE IF NOT EXISTS `job_requirement_evidence` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `target_job_id` BIGINT NOT NULL COMMENT 'target job id',
    `requirement_id` BIGINT NOT NULL COMMENT 'job requirement id',
    `project_evidence_id` BIGINT NOT NULL COMMENT 'project evidence id',
    `project_skill_evidence_id` BIGINT DEFAULT NULL COMMENT 'project skill evidence id',
    `evidence_ref_key` VARCHAR(64) NOT NULL COMMENT 'stable evidence reference',
    `match_type` VARCHAR(32) NOT NULL COMMENT 'SKILL_EXACT/JD_KEYWORD_EXACT/RELATED/PROJECT_TEXT',
    `coverage_level` VARCHAR(32) NOT NULL COMMENT 'STRONG/WEAK',
    `confidence_level` VARCHAR(32) NOT NULL COMMENT 'LOW/MEDIUM/HIGH',
    `evidence_source_type` VARCHAR(32) DEFAULT NULL COMMENT 'source type snapshot',
    `confirmed` TINYINT NOT NULL DEFAULT 0 COMMENT 'confirmed by user',
    `fallback` TINYINT NOT NULL DEFAULT 0 COMMENT 'degraded evidence cannot be strong',
    `evidence_text` TEXT DEFAULT NULL COMMENT 'evidence text snapshot',
    `match_reason` VARCHAR(1000) DEFAULT NULL COMMENT 'deterministic match explanation',
    `active_flag` TINYINT NOT NULL DEFAULT 1 COMMENT 'active in latest matrix refresh',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_requirement_evidence_ref` (`user_id`, `target_job_id`, `requirement_id`, `evidence_ref_key`),
    KEY `idx_requirement_evidence_requirement` (`requirement_id`, `active_flag`, `deleted`),
    KEY `idx_requirement_evidence_target` (`user_id`, `target_job_id`, `active_flag`, `deleted`),
    KEY `idx_requirement_evidence_project` (`project_evidence_id`, `project_skill_evidence_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='requirement to project evidence matrix';
