CREATE TABLE IF NOT EXISTS `vector_index_job` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `job_no` VARCHAR(64) NOT NULL COMMENT 'Vector index job number',
  `job_type` VARCHAR(64) NOT NULL COMMENT 'QUESTION_REBUILD, QUESTION_RETRY, KNOWLEDGE_REBUILD, KNOWLEDGE_RETRY, DELETE_OUTBOX_RETRY',
  `scope_type` VARCHAR(64) DEFAULT NULL COMMENT 'QUESTION, KNOWLEDGE, DELETE_OUTBOX',
  `scope_id` VARCHAR(128) DEFAULT NULL COMMENT 'Optional scope id or label',
  `status` VARCHAR(32) NOT NULL DEFAULT 'RUNNING' COMMENT 'RUNNING, SUCCESS, FAILED',
  `requested_count` INT DEFAULT NULL COMMENT 'Requested processing limit',
  `total_count` INT NOT NULL DEFAULT 0 COMMENT 'Matched or source item count',
  `success_count` INT NOT NULL DEFAULT 0 COMMENT 'Successful item count',
  `failed_count` INT NOT NULL DEFAULT 0 COMMENT 'Failed item count',
  `vector_updated` INT NOT NULL DEFAULT 0 COMMENT 'Upserted vector count',
  `vector_deleted` INT NOT NULL DEFAULT 0 COMMENT 'Deleted vector count',
  `started_at` DATETIME DEFAULT NULL COMMENT 'Job start time',
  `finished_at` DATETIME DEFAULT NULL COMMENT 'Job finish time',
  `duration_ms` BIGINT DEFAULT NULL COMMENT 'Job duration in milliseconds',
  `last_error` VARCHAR(1000) DEFAULT NULL COMMENT 'Last job error message',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '0 active, 1 deleted',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_vector_index_job_no` (`job_no`),
  KEY `idx_vector_index_job_type_status` (`job_type`, `status`, `created_at`),
  KEY `idx_vector_index_job_status` (`status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Vector index rebuild and retry job history';
