CREATE TABLE IF NOT EXISTS agent_metric_event_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  event_id VARCHAR(64) NOT NULL,
  event_code VARCHAR(80) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  user_id BIGINT NOT NULL,
  task_id BIGINT NULL,
  run_id BIGINT NULL,
  plan_date DATE NULL,
  target_job_id BIGINT NULL,
  request_id VARCHAR(128) NULL,
  source_page VARCHAR(80) NULL,
  target_path VARCHAR(255) NULL,
  notification_id VARCHAR(64) NULL,
  biz_type VARCHAR(80) NULL,
  biz_id VARCHAR(80) NULL,
  occurred_at DATETIME NOT NULL,
  accepted_at DATETIME NOT NULL,
  ingest_source VARCHAR(40) NOT NULL,
  metadata_json TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT DEFAULT 0,
  UNIQUE KEY uk_agent_metric_event_id (event_id),
  UNIQUE KEY uk_agent_metric_user_idempotency (user_id, idempotency_key, deleted),
  KEY idx_agent_metric_event_code (event_code),
  KEY idx_agent_metric_task (task_id),
  KEY idx_agent_metric_run (run_id),
  KEY idx_agent_metric_notification (notification_id),
  KEY idx_agent_metric_occurred_at (occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent metrics event fact table';
