CREATE TABLE IF NOT EXISTS `resume_suggestion` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `resume_id` BIGINT NOT NULL,
    `source_resume_version_id` BIGINT NOT NULL,
    `source_type` VARCHAR(40) NOT NULL DEFAULT 'AI',
    `source_id` BIGINT DEFAULT NULL,
    `source_version` VARCHAR(64) DEFAULT NULL,
    `section_key` VARCHAR(64) NOT NULL,
    `section_id` VARCHAR(128) DEFAULT NULL,
    `field_path` VARCHAR(255) DEFAULT NULL,
    `anchor_start` INT NOT NULL,
    `anchor_end` INT NOT NULL,
    `anchor_text_hash` CHAR(64) NOT NULL,
    `original_text` TEXT NOT NULL,
    `suggested_text` TEXT NOT NULL,
    `accepted_text` TEXT DEFAULT NULL,
    `evidence_refs_json` TEXT DEFAULT NULL,
    `risk_level` VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
    `rationale` VARCHAR(2000) DEFAULT NULL,
    `status` VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    `decision_version` INT NOT NULL DEFAULT 0,
    `applied_resume_version_id` BIGINT DEFAULT NULL,
    `undo_resume_version_id` BIGINT DEFAULT NULL,
    `decided_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_resume_suggestion_user_resume` (`user_id`, `resume_id`, `status`, `created_at`),
    KEY `idx_resume_suggestion_source_version` (`source_resume_version_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Sentence-level resume suggestion with stable source anchor';

CREATE TABLE IF NOT EXISTS `resume_suggestion_decision` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `suggestion_id` BIGINT NOT NULL,
    `decision_type` VARCHAR(24) NOT NULL COMMENT 'ACCEPT/REJECT/UNDO',
    `from_status` VARCHAR(24) NOT NULL,
    `to_status` VARCHAR(24) NOT NULL,
    `decision_version` INT NOT NULL,
    `result_resume_version_id` BIGINT DEFAULT NULL,
    `idempotency_key` VARCHAR(128) NOT NULL,
    `note` VARCHAR(1000) DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_resume_suggestion_decision_idempotency` (`user_id`, `idempotency_key`, `deleted`),
    KEY `idx_resume_suggestion_decision_suggestion` (`suggestion_id`, `decision_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Immutable resume suggestion decision and undo history';

CREATE TABLE IF NOT EXISTS `resume_claim_audit` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `resume_id` BIGINT NOT NULL,
    `resume_version_id` BIGINT NOT NULL,
    `source_hash` CHAR(64) NOT NULL,
    `audit_version` VARCHAR(32) NOT NULL,
    `status` VARCHAR(24) NOT NULL DEFAULT 'RUNNING',
    `claim_count` INT NOT NULL DEFAULT 0,
    `verified_count` INT NOT NULL DEFAULT 0,
    `partial_count` INT NOT NULL DEFAULT 0,
    `unsupported_count` INT NOT NULL DEFAULT 0,
    `risk_count` INT NOT NULL DEFAULT 0,
    `error_message` VARCHAR(1000) DEFAULT NULL,
    `completed_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_resume_claim_audit_user_version` (`user_id`, `resume_version_id`, `created_at`),
    KEY `idx_resume_claim_audit_status` (`status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Resume factual and quantitative claim audit run';

CREATE TABLE IF NOT EXISTS `resume_claim_audit_finding` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `audit_id` BIGINT NOT NULL,
    `user_id` BIGINT NOT NULL,
    `section_key` VARCHAR(64) NOT NULL,
    `claim_index` INT NOT NULL,
    `claim_type` VARCHAR(24) NOT NULL COMMENT 'FACT/QUANTIFIED',
    `claim_text` TEXT NOT NULL,
    `claim_hash` CHAR(64) NOT NULL,
    `quantities_json` TEXT DEFAULT NULL,
    `evidence_status` VARCHAR(24) NOT NULL COMMENT 'VERIFIED/PARTIAL/UNSUPPORTED/RISK',
    `evidence_refs_json` TEXT DEFAULT NULL,
    `reason` VARCHAR(1000) DEFAULT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `idx_resume_claim_finding_audit` (`audit_id`, `claim_index`),
    KEY `idx_resume_claim_finding_status` (`user_id`, `evidence_status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Claim-level evidence audit finding';
