CREATE TABLE IF NOT EXISTS `project_story_generation` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `project_evidence_id` BIGINT NOT NULL COMMENT 'project evidence id',
    `generation_type` VARCHAR(32) NOT NULL COMMENT 'RESUME_BULLET/STAR_STORY/INTERVIEW_QUESTIONS',
    `target_job_id` BIGINT DEFAULT NULL COMMENT 'optional target job id',
    `prompt_version` VARCHAR(64) DEFAULT NULL COMMENT 'generation prompt version',
    `result_text` MEDIUMTEXT DEFAULT NULL COMMENT 'full generated business result',
    `structured_result_json` JSON DEFAULT NULL COMMENT 'structured generated business result',
    `input_summary_json` JSON DEFAULT NULL COMMENT 'sanitized input summary for traceability',
    `ai_call_log_id` BIGINT DEFAULT NULL COMMENT 'ai call log id when model call is used',
    `trace_id` VARCHAR(64) DEFAULT NULL COMMENT 'trace id',
    `result_source` VARCHAR(32) NOT NULL DEFAULT 'LOCAL_GENERATOR' COMMENT 'AI/LOCAL_GENERATOR/FALLBACK',
    `accepted` TINYINT NOT NULL DEFAULT 0 COMMENT 'accepted by user',
    `status` VARCHAR(32) NOT NULL DEFAULT 'SUCCESS' COMMENT 'SUCCESS/FAILED',
    `error_message` VARCHAR(512) DEFAULT NULL COMMENT 'sanitized error summary',
    `prompt_tokens` INT DEFAULT NULL COMMENT 'prompt token estimate',
    `completion_tokens` INT DEFAULT NULL COMMENT 'completion token estimate',
    `total_tokens` INT DEFAULT NULL COMMENT 'total token estimate',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    PRIMARY KEY (`id`),
    KEY `idx_project_story_generation_project` (`project_evidence_id`, `deleted`, `created_at`),
    KEY `idx_project_story_generation_user` (`user_id`, `deleted`, `created_at`),
    KEY `idx_project_story_generation_type` (`project_evidence_id`, `generation_type`, `accepted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='project evidence interview material generation history';
