CREATE TABLE IF NOT EXISTS `job_application_package` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `package_no` VARCHAR(64) NOT NULL COMMENT 'business package number',
    `target_job_id` BIGINT DEFAULT NULL COMMENT 'target job id',
    `jd_analysis_id` BIGINT DEFAULT NULL COMMENT 'job description analysis id',
    `resume_id` BIGINT DEFAULT NULL COMMENT 'source resume id',
    `resume_version_id` BIGINT DEFAULT NULL COMMENT 'recommended resume version id',
    `match_report_id` BIGINT DEFAULT NULL COMMENT 'resume job match report id',
    `application_id` BIGINT DEFAULT NULL COMMENT 'created job application id',
    `company_name` VARCHAR(120) DEFAULT NULL COMMENT 'target company name',
    `job_title` VARCHAR(160) DEFAULT NULL COMMENT 'target job title',
    `readiness_level` VARCHAR(32) DEFAULT NULL COMMENT 'readiness level',
    `readiness_score` INT DEFAULT NULL COMMENT 'readiness score',
    `readiness_reason` VARCHAR(1000) DEFAULT NULL COMMENT 'readiness reason snapshot',
    `package_status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/READY/APPLIED/ARCHIVED',
    `snapshot_json` MEDIUMTEXT DEFAULT NULL COMMENT 'full package snapshot json',
    `checklist_json` MEDIUMTEXT DEFAULT NULL COMMENT 'checklist snapshot json',
    `actions_json` MEDIUMTEXT DEFAULT NULL COMMENT 'next action snapshot json',
    `project_evidence_ids_json` TEXT DEFAULT NULL COMMENT 'project evidence id snapshot json',
    `trace_id` VARCHAR(128) DEFAULT NULL COMMENT 'generation trace id',
    `result_source` VARCHAR(32) NOT NULL DEFAULT 'REAL' COMMENT 'REAL/FALLBACK/MOCK',
    `fallback` TINYINT NOT NULL DEFAULT 0 COMMENT 'whether result is degraded',
    `fallback_reason` VARCHAR(1000) DEFAULT NULL COMMENT 'fallback reason',
    `snapshot_version` INT NOT NULL DEFAULT 1 COMMENT 'snapshot version number',
    `refreshed_at` DATETIME DEFAULT NULL COMMENT 'last refresh time',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    PRIMARY KEY (`id`),
    KEY `idx_job_application_package_user_status` (`user_id`, `deleted`, `package_status`, `updated_at`),
    UNIQUE KEY `uk_job_application_package_no_live` (`package_no`, `deleted`),
    KEY `idx_job_application_package_target_job` (`target_job_id`, `deleted`),
    KEY `idx_job_application_package_jd_analysis` (`jd_analysis_id`, `deleted`),
    KEY `idx_job_application_package_resume_version` (`resume_version_id`, `deleted`),
    KEY `idx_job_application_package_match_report` (`match_report_id`, `deleted`),
    KEY `idx_job_application_package_application` (`application_id`, `deleted`),
    KEY `idx_job_application_package_trace` (`trace_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='persistent job application package snapshot';

CREATE TABLE IF NOT EXISTS `job_application_package_event` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT NOT NULL COMMENT 'owner user id',
    `package_id` BIGINT NOT NULL COMMENT 'job application package id',
    `event_type` VARCHAR(64) NOT NULL COMMENT 'package lifecycle event type',
    `event_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'business event time',
    `action_code` VARCHAR(64) DEFAULT NULL COMMENT 'executed package action code',
    `related_biz_type` VARCHAR(64) DEFAULT NULL COMMENT 'related business type',
    `related_biz_id` BIGINT DEFAULT NULL COMMENT 'related business id',
    `summary` VARCHAR(1000) DEFAULT NULL COMMENT 'safe event summary',
    `event_payload_json` MEDIUMTEXT DEFAULT NULL COMMENT 'event payload snapshot json',
    `trace_id` VARCHAR(128) DEFAULT NULL COMMENT 'related trace id',
    `result_source` VARCHAR(32) DEFAULT NULL COMMENT 'REAL/FALLBACK/MOCK',
    `fallback` TINYINT NOT NULL DEFAULT 0 COMMENT 'whether event result is degraded',
    `fallback_reason` VARCHAR(1000) DEFAULT NULL COMMENT 'fallback reason',
    `snapshot_version` INT DEFAULT NULL COMMENT 'package snapshot version when event happened',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'created time',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updated time',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logic delete flag',
    PRIMARY KEY (`id`),
    KEY `idx_job_application_package_event_package` (`package_id`, `deleted`, `event_time`),
    KEY `idx_job_application_package_event_user` (`user_id`, `deleted`, `event_time`),
    KEY `idx_job_application_package_event_type` (`event_type`, `deleted`, `event_time`),
    KEY `idx_job_application_package_event_related` (`related_biz_type`, `related_biz_id`, `deleted`),
    KEY `idx_job_application_package_event_trace` (`trace_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='job application package lifecycle event';
