CREATE TABLE IF NOT EXISTS `agent_run` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `user_id` BIGINT NOT NULL COMMENT 'User id',
  `agent_type` VARCHAR(64) NOT NULL COMMENT 'Agent type',
  `target_job_id` BIGINT NULL COMMENT 'Target job id',
  `plan_date` DATE NULL COMMENT 'Daily plan date',
  `trigger_type` VARCHAR(64) NOT NULL DEFAULT 'MANUAL' COMMENT 'Trigger type',
  `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'Run status',
  `input_snapshot_json` JSON NULL COMMENT 'Input context snapshot',
  `output_json` JSON NULL COMMENT 'Structured output',
  `raw_output_text` LONGTEXT NULL COMMENT 'Raw AI output',
  `prompt_type` VARCHAR(128) NULL COMMENT 'Prompt type',
  `prompt_version_id` BIGINT NULL COMMENT 'Prompt version id',
  `model_name` VARCHAR(128) NULL COMMENT 'Model name',
  `trace_id` VARCHAR(128) NULL COMMENT 'Trace id',
  `ai_call_log_id` BIGINT NULL COMMENT 'AI call log id',
  `token_input` INT NULL DEFAULT 0 COMMENT 'Input tokens',
  `token_output` INT NULL DEFAULT 0 COMMENT 'Output tokens',
  `duration_ms` BIGINT NULL DEFAULT 0 COMMENT 'Duration in milliseconds',
  `error_code` VARCHAR(128) NULL COMMENT 'Error code',
  `error_message` VARCHAR(1024) NULL COMMENT 'Error message',
  `started_at` DATETIME NULL COMMENT 'Started time',
  `finished_at` DATETIME NULL COMMENT 'Finished time',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'Logic delete flag',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  PRIMARY KEY (`id`),
  KEY `idx_agent_run_user_created` (`user_id`, `created_at`),
  KEY `idx_agent_run_user_target_date` (`user_id`, `target_job_id`, `plan_date`, `status`),
  KEY `idx_agent_run_status` (`status`, `created_at`),
  KEY `idx_agent_run_trace` (`trace_id`),
  KEY `idx_agent_run_ai_log` (`ai_call_log_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent run record';

CREATE TABLE IF NOT EXISTS `agent_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `user_id` BIGINT NOT NULL COMMENT 'User id',
  `agent_run_id` BIGINT NOT NULL COMMENT 'Agent run id',
  `target_job_id` BIGINT NULL COMMENT 'Target job id',
  `candidate_id` VARCHAR(64) NULL COMMENT 'Candidate task id',
  `task_type` VARCHAR(64) NOT NULL COMMENT 'Task type',
  `title` VARCHAR(255) NOT NULL COMMENT 'Task title',
  `description` TEXT NULL COMMENT 'Task description',
  `reason` TEXT NULL COMMENT 'Recommendation reason',
  `priority` VARCHAR(32) NOT NULL DEFAULT 'MEDIUM' COMMENT 'Priority',
  `estimated_minutes` INT NOT NULL DEFAULT 30 COMMENT 'Estimated minutes',
  `related_skill_code` VARCHAR(128) NULL COMMENT 'Related skill code',
  `related_skill_name` VARCHAR(128) NULL COMMENT 'Related skill name',
  `related_biz_type` VARCHAR(64) NULL COMMENT 'Related business type',
  `related_biz_id` BIGINT NULL COMMENT 'Related business id',
  `action_url` VARCHAR(512) NULL COMMENT 'Frontend action URL',
  `status` VARCHAR(32) NOT NULL DEFAULT 'TODO' COMMENT 'Task status',
  `skip_reason` VARCHAR(512) NULL COMMENT 'Skip reason',
  `due_date` DATE NOT NULL COMMENT 'Task due date',
  `started_at` DATETIME NULL COMMENT 'Started time',
  `completed_at` DATETIME NULL COMMENT 'Completed time',
  `skipped_at` DATETIME NULL COMMENT 'Skipped time',
  `sort_order` INT NOT NULL DEFAULT 0 COMMENT 'Sort order',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'Logic delete flag',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  PRIMARY KEY (`id`),
  KEY `idx_agent_task_user_due` (`user_id`, `due_date`, `status`),
  KEY `idx_agent_task_run` (`agent_run_id`),
  KEY `idx_agent_task_user_target` (`user_id`, `target_job_id`),
  KEY `idx_agent_task_status` (`status`, `due_date`),
  KEY `idx_agent_task_related` (`related_biz_type`, `related_biz_id`),
  KEY `idx_agent_task_skill` (`related_skill_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent suggested user task';
